public class LinkedListMain {
    public static void main(String[] args) {
        System.out.println("===== SINGLY LINKED LIST INSERTION =====");
        insertionSLL sllInsert = new insertionSLL();
        sllInsert.insertAtBeginning(20);
        sllInsert.insertAtBeginning(10);
        sllInsert.insertAtEnd(30);
        sllInsert.insertAtEnd(40);
        sllInsert.insertAtPosition(25, 3);
        sllInsert.display();
        System.out.println("\n===== SINGLY LINKED LIST DELETION =====");
        deletionSLL sllDelete = new deletionSLL();
        sllDelete.insert(10);
        sllDelete.insert(20);
        sllDelete.insert(30);
        sllDelete.insert(40);
        System.out.println("Before Deletion:");
        sllDelete.display();
        sllDelete.deleteBeginning();
        sllDelete.deleteEnd();
        sllDelete.deleteValue(30);
        System.out.println("After Deletion:");
        sllDelete.display();
        System.out.println("\n===== SINGLY LINKED LIST TRAVERSAL =====");
        traversalSLL sllTraversal = new traversalSLL();
        sllTraversal.insertAtEnd(10);
        sllTraversal.insertAtEnd(20);
        sllTraversal.insertAtEnd(30);
        sllTraversal.printList();
        System.out.println("Length: " + sllTraversal.length());
        System.out.println("Search 20: " + (sllTraversal.search(20) ? "Found" : "Not Found"));
        System.out.println("\n===== DOUBLY LINKED LIST INSERTION =====");
        insertionDLL dllInsert = new insertionDLL();
        dllInsert.insertAtBeginning(20);
        dllInsert.insertAtBeginning(10);
        dllInsert.insertAtEnd(30);
        dllInsert.insertAtEnd(40);
        dllInsert.insertAtPosition(25, 3);
        System.out.println("Forward:");
        dllInsert.displayForward();
        System.out.println("Backward:");
        dllInsert.displayBackward();
        System.out.println("\n===== DOUBLY LINKED LIST DELETION =====");
        deletionDLL dllDelete = new deletionDLL();
        dllDelete.insert(10);
        dllDelete.insert(20);
        dllDelete.insert(30);
        dllDelete.insert(40);
        System.out.println("Before Deletion:");
        dllDelete.display();
        dllDelete.deleteBeginning();
        dllDelete.deleteEnd();
        dllDelete.deleteValue(30);
        System.out.println("After Deletion:");
        dllDelete.display();
        System.out.println("\n===== DOUBLY LINKED LIST TRAVERSAL =====");
        traversalDLL dllTraversal = new traversalDLL();
        dllTraversal.insertAtEnd(10);
        dllTraversal.insertAtEnd(20);
        dllTraversal.insertAtEnd(30);
        System.out.println("Forward:");
        dllTraversal.printForward();
        System.out.println("Backward:");
        dllTraversal.printBackward();
        System.out.println("Length: " + dllTraversal.length());
        System.out.println("Search 20: " + (dllTraversal.search(20) ? "Found" : "Not Found"));
        System.out.println("\nName: SYEDA WANIYA SAJJAD");
        System.out.println("Seat Number: EB25210006106");
    }
}